Repository TEAM-NEO/NEO_Backend, pull requests merged in 2023-08, with the labels that each got.

#11 feat : CI 테스트를 위한 환경변수 설정
  .gitignore
  docker-compose.yml
  docker/.env
  needeachother/.gitignore
  needeachother/src/main/resources/application.yml
Labels: ⚙️ 기타 / 세팅

#12 feat : 유저 정보 획득 기능 구현 완료 PR (#8)
  needeachother/src/main/java/com/neo/needeachother/common/enums/NEOErrorCode.java
  needeachother/src/main/java/com/neo/needeachother/common/exception/NEOUnexpectedException.java
  needeachother/src/main/java/com/neo/needeachother/common/response/NEOResponseBody.java
  needeachother/src/main/java/com/neo/needeachother/config/NEOJacksonConfig.java
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserInformationController.java
  needeachother/src/main/java/com/neo/needeachother/users/document/NEOStarInfoDocument.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOFanInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOPublicFanInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOPublicStarInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOStarInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOFanEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOStarEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOStarTypeEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/enums/NEOStarDetailClassification.java
  needeachother/src/main/java/com/neo/needeachother/users/filter/NEOInfoDtoJsonFilter.java
  needeachother/src/main/java/com/neo/needeachother/users/mapper/NEOStarMapper.java
  needeachother/src/main/java/com/neo/needeachother/users/repository/NEOStarCustomInfoRepository.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserInformationService.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserServiceImpl.java
Labels: 🪄 기능구현

#20 fix : MapStruct 라이브러리 삭제 및 @MappedSuperclass와 @Entity를 잘못 사용한 부분 hotfix(#19)
  needeachother/build.gradle
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserInformationController.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOUserEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/mapper/NEOStarMapper.java
  needeachother/src/main/resources/application.yml
Labels: 🔧 오류 수정

#26 fix : CI build 에러 수정
  .github/workflows/CI.yml
  needeachother/Dockerfile
Labels: 🔧 오류 수정

#27 pr : 사용자 정보 변경 API 개발
  needeachother/src/main/java/com/neo/needeachother/common/response/NEOResponseBody.java
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserExceptionAdvisor.java
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserInformationController.java
  needeachother/src/main/java/com/neo/needeachother/users/document/NEOStarInfoDocument.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOChangeableInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOCustomStarInformation.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOPublicStarInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOStarInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOStarEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOStarTypeEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOUserEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/enums/NEOStarDetailClassification.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserInformationService.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserServiceImpl.java
Labels: 🪄 기능구현

#32 feat : 회원 정보 삭제 기능 개발 (#31)
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserExceptionAdvisor.java
  needeachother/src/main/java/com/neo/needeachother/users/controller/NEOUserInformationController.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOChangeableInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/dto/NEOStarInfoDto.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOStarEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/entity/NEOUserEntity.java
  needeachother/src/main/java/com/neo/needeachother/users/enums/NEOStarDetailClassification.java
  needeachother/src/main/java/com/neo/needeachother/users/enums/NEOUserOrder.java
  needeachother/src/main/java/com/neo/needeachother/users/exception/NEOUserExpectedException.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserInformationService.java
  needeachother/src/main/java/com/neo/needeachother/users/service/NEOUserServiceImpl.java
Labels: 🪄 기능구현
